FROM oryd/xgoreleaser:test-build

WORKDIR /home/ory/test/no-cgo

ADD test/no-cgo/go.mod ./
RUN go mod download

ENV RELEASE_NAME=v0.0.0-alpha.1
ENV DOCKER_SHORT_TAG=v0.0.0-alpha.1

ADD . /home/ory/

ENTRYPOINT ["goreleaser"]
CMD ["--snapshot", "--skip=publish,sign", "--clean"]
